import "./globals.css";
import { Ubuntu } from "next/font/google";
import Providers from "./Providers";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--font-main",
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Trivia App 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ubuntu.variable}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
